# src/eCrowd/MainBundle/Resources/config/doctrine/User.orm.yml
eCrowd\MainBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: eCrowd\MainBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    properties:
    fields:
      firstname:
        type: string
        length: 255
        nullable: true
      lastname:
        type: string
        length: 255
        nullable: true
      facebook_id:
        type: string
        length: 255
        nullable: true
      facebook_access_token:
        type: string
        length: 255
        nullable: true
      google_id:
        type: string
        length: 255
        nullable: true
      google_access_token:
        type: string
        length: 255
        nullable: true
        
      
